---
title: "Preprocessing NMR Metabolomics"
author: "Zhongyi (James) Guo"
date: "`r Sys.Date()`"
output: html_document
---

We extracted NMR metabolomics using `Table Exporter`. This file contains NMR metabolomics data cleaning and merging.

```{r setup, warning=FALSE, message=FALSE}
library(tidyverse)
library(readr)
setwd("~/ukb-nmr/scripts/data_prep")
```

## Data Cleaning

```{r import_nmr_metabolomics_both_parts, warning=FALSE, message=FALSE}
nmr_met_1 <- read_csv('~/pca_metabolomics/table_exporter/output/nmr_met_1_participant.csv')
nmr_met_2 <- read_csv('~/pca_metabolomics/table_exporter/output/nmr_met_2_participant.csv')
nmr_met <- merge(nmr_met_1, nmr_met_2, by = "eid")
dim(nmr_met)
```

There were 228,973 participants and 252 columns (251 metabolites + 1 `eid`.)

```{r map_field_titles}
# remove instance number and "p"
fields_of_interest <- sub("^p", "", sub("_.*", "", colnames(nmr_met)[-1]))

# extract field titles from field dictionary
field_dictionary <- read_tsv('~/pca_metabolomics/Showcase metadata/field.tsv')
field_titles <- field_dictionary |> 
  filter(field_id %in% fields_of_interest) |> 
  slice(match(fields_of_interest, field_id)) |>
  pull(title)

colnames(nmr_met) <- c('eid', field_titles)
```

## Save the Merged NMR Metabolomics Data

```{r save_cleaned_nmr_met}
write.csv(nmr_met, '~/pca_metabolomics/cleaned_data/nmr_met_cleaned.csv', row.names = FALSE)
```

```{r sessionInfo}
sessionInfo()
```
